name: Smoke Tests Workflow

on:
  workflow_dispatch:

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          server-id: github

      - name: Run Tests
        run: mvn -q -Dtest=Smoke test

      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: target/cucumber-reports/cucumber-html-report.html
 
      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: target/cucumber-reports/cucumber-html-report.html
