name: Maven V.1

on:
  workflow_dispatch: 
    inputs:
      name: 
        description: "What is your name?"
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Hello Step
      env:
        ENTERED_NAME: ${{ github.event.inputs.name }}
      run: echo "Hello! ${ENTERED_NAME}"
      
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    # - name: Set up Chrome
    #   uses: browser-actions/setup-chrome@v1
    # - run: chrome --version

    - name: Run Test with Maven
      run: |
            mvn test -DTest=Run_Smoke_Test.java -q
            echo "check target folder"

    - name: Clean Github Pages branch
      run: |
        git branch -D origin gh-pages
        git checkout --orphan gh-pages
        # git rm -rf .
        

    - name: Move Cucumber reports to new directory
      run: | 
        mkdir docs
        cp -r target/cucumber-reports/* docs/

    - name: Deploy to Pages!
      run: |
        git config --local user.email "keindavey@gmail.com"
        git config --local user.name "keidavey"
        git add docs/*
        git commit -m "Update Github Pages"
        git remote set-url origin https://keidavey:${{secrets.ACTIONS_TOKEN}}@github.com/keidavey/GithubActionsPages.git
        git push origin gh-pages
